import { booleanProp, numberProp, optionsProp, selectProp, textProp, textareaProp, urlProp } from '../props';
import type { WidgetDefinition } from '../types';

export const CONTENT_WIDGETS: WidgetDefinition[] = [
  {
    type: 'heading',
    label: 'Heading',
    category: 'content',
    icon: 'heading',
    description: 'Section title rendered as h1–h6.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { text: 'Heading', level: 'h2' },
    defaultStyle: { 'font-size': '28px', 'font-weight': '700', 'line-height': '1.2', margin: '0' },
    propSchema: [
      textProp('text', 'Text'),
      selectProp(
        'level',
        'Level',
        ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'].map((level) => ({ label: level.toUpperCase(), value: level })),
        'appearance',
      ),
    ],
  },
  {
    type: 'text',
    label: 'Text',
    category: 'content',
    icon: 'text',
    description: 'Paragraph or label text.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
    defaultStyle: { 'font-size': '15px', 'line-height': '1.6', margin: '0' },
    propSchema: [textareaProp('text', 'Text'), selectProp(
      'weight',
      'Weight',
      [
        { label: 'Regular', value: '400' },
        { label: 'Medium', value: '500' },
        { label: 'Semi bold', value: '600' },
        { label: 'Bold', value: '700' },
      ],
      'appearance',
    )],
  },
  {
    type: 'badge',
    label: 'Badge',
    category: 'content',
    icon: 'badge',
    description: 'Small status pill.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { text: 'New', variant: 'soft' },
    propSchema: [
      textProp('text', 'Text'),
      selectProp(
        'variant',
        'Variant',
        [
          { label: 'Solid', value: 'solid' },
          { label: 'Soft', value: 'soft' },
          { label: 'Outline', value: 'outline' },
        ],
        'appearance',
      ),
    ],
  },
  {
    type: 'alert',
    label: 'Alert',
    category: 'content',
    icon: 'alert',
    description: 'Inline message with an optional title.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { title: 'Heads up', text: 'Something worth mentioning.', variant: 'info' },
    defaultStyle: { padding: '14px 16px' },
    propSchema: [
      textProp('title', 'Title'),
      textareaProp('text', 'Message'),
      selectProp(
        'variant',
        'Variant',
        [
          { label: 'Info', value: 'info' },
          { label: 'Success', value: 'success' },
          { label: 'Warning', value: 'warning' },
          { label: 'Danger', value: 'danger' },
        ],
        'appearance',
      ),
    ],
  },
  {
    type: 'icon',
    label: 'Icon',
    category: 'content',
    icon: 'icon',
    description: 'Material style glyph rendered as inline SVG.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { name: 'star', size: 24 },
    propSchema: [
      selectProp(
        'name',
        'Icon',
        [
          'star',
          'check',
          'close',
          'search',
          'settings',
          'user',
          'mail',
          'phone',
          'home',
          'cart',
          'heart',
          'arrow-right',
          'download',
          'upload',
          'menu',
          'plus',
          'trash',
          'edit',
        ].map((name) => ({ label: name, value: name })),
        'content',
      ),
      numberProp('size', 'Size (px)', 'appearance', { min: 8, max: 128 }),
    ],
  },
  {
    type: 'link',
    label: 'Link',
    category: 'content',
    icon: 'link',
    description: 'Anchor pointing at an external URL or an internal route.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { label: 'Learn more', href: '#', openInNewTab: false },
    propSchema: [
      textProp('label', 'Label'),
      urlProp('href', 'URL / route'),
      booleanProp('openInNewTab', 'Open in new tab'),
    ],
  },
  {
    type: 'list',
    label: 'List',
    category: 'content',
    icon: 'list',
    description: 'Bulleted or numbered list built from a line separated list of items.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { items: 'First item\nSecond item\nThird item', ordered: false },
    defaultStyle: { 'padding-left': '20px', margin: '0' },
    propSchema: [
      optionsProp('items', 'Items (one per line)'),
      booleanProp('ordered', 'Numbered list', 'appearance'),
    ],
  },
];
