import { booleanProp, numberProp, optionsProp, selectProp, textProp, textareaProp } from '../props';
import type { WidgetDefinition } from '../types';

const VARIANTS = [
  { label: 'Primary', value: 'primary' },
  { label: 'Secondary', value: 'secondary' },
  { label: 'Outline', value: 'outline' },
  { label: 'Ghost', value: 'ghost' },
  { label: 'Danger', value: 'danger' },
];

export const INPUT_WIDGETS: WidgetDefinition[] = [
  {
    type: 'button',
    label: 'Button',
    category: 'input',
    icon: 'button',
    description: 'Clickable action button.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { label: 'Click me', variant: 'primary', size: 'md', buttonType: 'button', fullWidth: false },
    propSchema: [
      textProp('label', 'Label'),
      selectProp('variant', 'Variant', VARIANTS, 'appearance'),
      selectProp(
        'size',
        'Size',
        [
          { label: 'Small', value: 'sm' },
          { label: 'Medium', value: 'md' },
          { label: 'Large', value: 'lg' },
        ],
        'appearance',
      ),
      selectProp(
        'buttonType',
        'Type',
        [
          { label: 'button', value: 'button' },
          { label: 'submit', value: 'submit' },
          { label: 'reset', value: 'reset' },
        ],
        'behaviour',
      ),
      booleanProp('fullWidth', 'Full width', 'appearance'),
    ],
  },
  {
    type: 'text-input',
    label: 'Text input',
    category: 'input',
    icon: 'input',
    description: 'Single line input with label and helper text.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { label: 'Label', placeholder: 'Type here…', inputType: 'text', name: 'field', required: false, helper: '' },
    defaultStyle: { display: 'flex', 'flex-direction': 'column', gap: '6px' },
    propSchema: [
      textProp('label', 'Label'),
      textProp('placeholder', 'Placeholder'),
      textProp('helper', 'Helper text'),
      textProp('name', 'Field name', 'behaviour'),
      selectProp(
        'inputType',
        'Type',
        ['text', 'email', 'password', 'number', 'tel', 'date', 'url'].map((value) => ({ label: value, value })),
        'behaviour',
      ),
      booleanProp('required', 'Required'),
    ],
  },
  {
    type: 'textarea',
    label: 'Text area',
    category: 'input',
    icon: 'textarea',
    description: 'Multi line input.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { label: 'Message', placeholder: 'Write something…', rows: 4, name: 'message', required: false },
    defaultStyle: { display: 'flex', 'flex-direction': 'column', gap: '6px' },
    propSchema: [
      textProp('label', 'Label'),
      textareaProp('placeholder', 'Placeholder'),
      textProp('name', 'Field name', 'behaviour'),
      numberProp('rows', 'Rows', 'appearance', { min: 2, max: 20 }),
      booleanProp('required', 'Required'),
    ],
  },
  {
    type: 'select',
    label: 'Select',
    category: 'input',
    icon: 'select',
    description: 'Dropdown built from `value: Label` lines.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { label: 'Choose', options: 'one: First option\ntwo: Second option', name: 'choice', placeholder: 'Select…', required: false },
    defaultStyle: { display: 'flex', 'flex-direction': 'column', gap: '6px' },
    propSchema: [
      textProp('label', 'Label'),
      optionsProp('options', 'Options (value: Label)'),
      textProp('placeholder', 'Placeholder'),
      textProp('name', 'Field name', 'behaviour'),
      booleanProp('required', 'Required'),
    ],
  },
  {
    type: 'checkbox',
    label: 'Checkbox',
    category: 'input',
    icon: 'checkbox',
    description: 'Boolean toggle with a label.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { label: 'Accept the terms', checked: false, name: 'terms' },
    defaultStyle: { display: 'flex', 'align-items': 'center', gap: '8px' },
    propSchema: [textProp('label', 'Label'), textProp('name', 'Field name', 'behaviour'), booleanProp('checked', 'Checked by default')],
  },
  {
    type: 'switch',
    label: 'Switch',
    category: 'input',
    icon: 'switch',
    description: 'On/off toggle.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { label: 'Enable notifications', checked: true, name: 'notifications' },
    defaultStyle: { display: 'flex', 'align-items': 'center', gap: '10px' },
    propSchema: [textProp('label', 'Label'), textProp('name', 'Field name', 'behaviour'), booleanProp('checked', 'On by default')],
  },
];
