import { booleanProp, numberProp, selectProp, textProp } from '../props';
import type { WidgetDefinition } from '../types';

export const LAYOUT_WIDGETS: WidgetDefinition[] = [
  {
    type: 'container',
    label: 'Container',
    category: 'layout',
    icon: 'container',
    description: 'A flexible block that holds other widgets. The workhorse of every layout.',
    isContainer: true,
    maxChildren: -1,
    defaultProps: { label: 'Container', tag: 'div' },
    defaultStyle: { display: 'flex', 'flex-direction': 'column', gap: '12px', padding: '16px' },
    propSchema: [
      textProp('label', 'Empty state label', 'content', { help: 'Shown in the canvas while the container is empty.' }),
      selectProp(
        'tag',
        'HTML element',
        [
          { label: 'div', value: 'div' },
          { label: 'section', value: 'section' },
          { label: 'main', value: 'main' },
          { label: 'header', value: 'header' },
          { label: 'footer', value: 'footer' },
          { label: 'aside', value: 'aside' },
        ],
        'behaviour',
      ),
    ],
  },
  {
    type: 'row',
    label: 'Row',
    category: 'layout',
    icon: 'row',
    description: 'Horizontal flex layout.',
    isContainer: true,
    maxChildren: -1,
    defaultProps: { label: 'Row', wrap: true },
    defaultStyle: { display: 'flex', 'flex-direction': 'row', 'align-items': 'center', gap: '12px' },
    propSchema: [
      textProp('label', 'Empty state label'),
      booleanProp('wrap', 'Wrap to next line', 'appearance'),
    ],
  },
  {
    type: 'column',
    label: 'Column',
    category: 'layout',
    icon: 'column',
    description: 'Vertical flex layout.',
    isContainer: true,
    maxChildren: -1,
    defaultProps: { label: 'Column' },
    defaultStyle: { display: 'flex', 'flex-direction': 'column', gap: '12px' },
    propSchema: [textProp('label', 'Empty state label')],
  },
  {
    type: 'grid',
    label: 'Grid',
    category: 'layout',
    icon: 'grid',
    description: 'CSS grid with a configurable number of columns.',
    isContainer: true,
    maxChildren: -1,
    defaultProps: { label: 'Grid', columns: 3 },
    defaultStyle: { display: 'grid', gap: '16px' },
    propSchema: [textProp('label', 'Empty state label'), numberProp('columns', 'Columns', 'appearance', { min: 1, max: 12 })],
  },
  {
    type: 'stack',
    label: 'Stack',
    category: 'layout',
    icon: 'stack',
    description: 'Positioned container: children are stacked on top of each other.',
    isContainer: true,
    maxChildren: -1,
    defaultProps: { label: 'Stack', minHeight: 220 },
    defaultStyle: { position: 'relative', 'min-height': '220px', padding: '0px' },
    propSchema: [textProp('label', 'Empty state label'), numberProp('minHeight', 'Min height (px)', 'appearance', { min: 0, max: 2000 })],
  },
  {
    type: 'card',
    label: 'Card',
    category: 'layout',
    icon: 'card',
    description: 'Elevated surface with an optional title and subtitle.',
    isContainer: true,
    maxChildren: -1,
    defaultProps: { title: 'Card title', subtitle: 'A short description', elevated: true, label: 'Card' },
    defaultStyle: { display: 'flex', 'flex-direction': 'column', gap: '12px' },
    propSchema: [
      textProp('title', 'Title'),
      textProp('subtitle', 'Subtitle'),
      textProp('label', 'Empty state label'),
      booleanProp('elevated', 'Show shadow', 'appearance'),
    ],
  },
  {
    type: 'divider',
    label: 'Divider',
    category: 'layout',
    icon: 'divider',
    description: 'Horizontal or vertical rule.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { orientation: 'horizontal', thickness: 1 },
    propSchema: [
      selectProp(
        'orientation',
        'Orientation',
        [
          { label: 'Horizontal', value: 'horizontal' },
          { label: 'Vertical', value: 'vertical' },
        ],
        'appearance',
      ),
      numberProp('thickness', 'Thickness (px)', 'appearance', { min: 1, max: 12 }),
    ],
  },
  {
    type: 'spacer',
    label: 'Spacer',
    category: 'layout',
    icon: 'spacer',
    description: 'Empty space with a fixed height.',
    isContainer: false,
    maxChildren: 0,
    defaultProps: { size: 24 },
    defaultStyle: { height: '24px' },
    propSchema: [numberProp('size', 'Size (px)', 'appearance', { min: 0, max: 600 })],
  },
  {
    type: 'form',
    label: 'Form',
    category: 'layout',
    icon: 'form',
    description: 'Form wrapper with a submit button. Generates an Angular form binding.',
    isContainer: true,
    maxChildren: -1,
    defaultProps: { label: 'Form', submitLabel: 'Submit', method: 'post' },
    defaultStyle: { display: 'flex', 'flex-direction': 'column', gap: '14px' },
    propSchema: [
      textProp('label', 'Empty state label'),
      textProp('submitLabel', 'Submit button label'),
      selectProp(
        'method',
        'Method',
        [
          { label: 'POST', value: 'post' },
          { label: 'GET', value: 'get' },
        ],
        'behaviour',
      ),
    ],
  },
];
