import { BREAKPOINTS, type AppNode, type CssMap, type ThemeTokens } from '@appstudio/schema';
import { derivedStyle, nodeClasses } from '@appstudio/widgets';
import type { ComponentPlan } from './plan';

/** The stable, unique class of a node (`text-1ab2c`). */
export function nodeSelectorClass(node: AppNode): string {
  return nodeClasses(node)[1];
}

function declarations(style: CssMap, indent = '  '): string {
  return Object.entries(style)
    .filter(([, value]) => value !== '' && value !== null && value !== undefined)
    .map(([property, value]) => `${indent}${property}: ${value};`)
    .join('\n');
}

interface StyleEntry {
  node: AppNode;
  base: CssMap;
  breakpoints: Record<string, CssMap>;
}

/**
 * Styles owned by a component: its own nodes only. Nodes that were extracted
 * into a child component bring their own stylesheet, so the walk stops there.
 */
function collectStyles(plan: ComponentPlan, byNodeId: Map<string, ComponentPlan>): StyleEntry[] {
  const entries: StyleEntry[] = [];
  const walk = (node: AppNode, isRoot: boolean): void => {
    if (!isRoot) {
      const owner = byNodeId.get(node.id);
      if (owner && owner !== plan) {
        return;
      }
    }
    entries.push({
      node,
      base: { ...derivedStyle(node), ...node.style },
      breakpoints: (node.styles ?? {}) as Record<string, CssMap>,
    });
    node.children.forEach((child) => walk(child, false));
  };
  walk(plan.node, true);
  return entries;
}

/**
 * Component stylesheet: base rules, responsive overrides as media queries, then
 * the user's own imported CSS verbatim (scoped by Angular to this component).
 */
export function emitComponentStyles(plan: ComponentPlan, byNodeId: Map<string, ComponentPlan>): string {
  const entries = collectStyles(plan, byNodeId);
  const chunks: string[] = [];

  const widget = plan.node.type;
  const customFiles = entries.filter((entry) => entry.node.css && entry.node.css.trim().length > 0);

  chunks.push(`/* Generated by AppStudio — ${describe(plan)}.
 * Edit freely: re-exporting from the studio overwrites this file,
 * so keep hand written tweaks in the studio's custom CSS field or a separate file.
 */`);
  chunks.push(':host {\n  display: block;\n}');

  const baseRules = entries
    .filter((entry) => Object.keys(entry.base).length > 0)
    .map((entry) => `.${nodeSelectorClass(entry.node)} {\n${declarations(entry.base)}\n}`);
  if (baseRules.length > 0) {
    chunks.push(baseRules.join('\n\n'));
  }

  for (const breakpoint of BREAKPOINTS) {
    if (!breakpoint.media) {
      continue;
    }
    const rules = entries
      .filter((entry) => Object.keys(entry.breakpoints[breakpoint.id] ?? {}).length > 0)
      .map((entry) => {
        const css = entry.breakpoints[breakpoint.id] ?? {};
        return `  .${nodeSelectorClass(entry.node)} {\n${declarations(css, '    ')}\n  }`;
      });
    if (rules.length > 0) {
      chunks.push(`/* ${breakpoint.label} — ${breakpoint.description} */\n@media ${breakpoint.media} {\n${rules.join('\n\n')}\n}`);
    }
  }

  for (const entry of customFiles) {
    const fileName = entry.node.cssFileName ?? 'custom.css';
    chunks.push(
      `/* ---- Imported by the user: ${fileName}${
        entry.node.id === plan.node.id ? '' : ` (widget ${widget} ${nodeSelectorClass(entry.node)})`
      } ---- */\n${(entry.node.css ?? '').trim()}`,
    );
  }

  if (plan.page?.css && plan.page.css.trim().length > 0) {
    chunks.push(`/* ---- Page stylesheet imported by the user: ${plan.page.cssFileName ?? 'page.css'} ---- */\n${plan.page.css.trim()}`);
  }

  return `${chunks.join('\n\n')}\n`;
}

export function describe(plan: ComponentPlan): string {
  if (plan.kind === 'page') {
    return `page "${plan.page?.name ?? ''}" (${plan.className})`;
  }
  return `${plan.kind} "${plan.className}"`;
}

/** Root stylesheet of the generated app: theme tokens, resets and widget base CSS. */
export function emitGlobalStyles(theme: ThemeTokens, baseCss: string): string {
  return `/* Generated by AppStudio.
 * Theme tokens live in :root so components can reference var(--as-*).
 */
:root {
  --as-primary: ${theme.primary};
  --as-on-primary: ${theme.onPrimary};
  --as-secondary: ${theme.secondary};
  --as-accent: ${theme.accent};
  --as-surface: ${theme.surface};
  --as-surface-alt: ${theme.surfaceAlt};
  --as-text: ${theme.text};
  --as-text-muted: ${theme.textMuted};
  --as-border: ${theme.border};
  --as-radius: ${theme.radius}px;
  --as-space: ${theme.spacing}px;
  --as-font-heading: ${theme.fontHeading};
  --as-font-body: ${theme.fontBody};
  --as-shadow: ${theme.shadow};
  font-size: ${theme.fontScale}px;
}

*,
*::before,
*::after {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  padding: 0;
}

body {
  font-family: var(--as-font-body);
  color: var(--as-text);
  background: var(--as-surface);
  -webkit-font-smoothing: antialiased;
}

h1,
h2,
h3,
h4,
h5,
h6,
p {
  margin: 0;
}

/* ---- Widget base styles ---- */
${baseCss}
`;
}
